[anchor]
version = "0.32.1"
solana = "1.18.0"

[toolchain]
anchor_version = "0.30.1"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[programs]
devnet = { amm = "4oinKHPtdGALR4aVCtns8KqmZ5sqfDa3y9esqe6zYPi4" }

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
