[package]
name = "amm"
version = "0.1.0"
description = "AMM Module for Solana DeFi Protocol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["no-entrypoint", "no-idl", "no-log-ix-name"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["token"] }
solana-program = "1.18.0"
